# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BucketList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BucketList
  pod 'MessageKit'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'NotificationBannerSwift', '3.0.0'
  pod 'Firebase/Storage'

end
